sudo: false
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
rust:
- stable
- beta
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- "travis-cargo build &&\n travis-cargo --only stable doc"
after_success:
- travis-cargo doc-upload
- travis-cargo coveralls --no-sudo --verify
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: S6K8swCIKfgKuQT+6lNEB3z4aqJGU3xrmB/yUS25/vUv4CpMeQPHdUg6p9zBNDeANZ0zyy/+eklcq6c19X6ZdYhevTO6C1yeBRQFGAlq0V8WwjPUy8Pf/vGsSapkCFBuxHc9SDQIBqNaXRXq/eePizy+vQJQ+Mb4MEKZEgWinuF+iSzKpFwqOF0zS2Qd4fRwbgyRW5f6Wup/EnSNZRnMnmOYMtjo61ZE1H5ECtZ4VwmnOvoqCJ+vEZA5HQnnFwXqIzaoxLRHgJmRBF9Aogqsax5jzD+JFwmWs1kbBFjtWsbD0gLbAL+Ta+rGpxKLtzQTp12Jo9JHdq1bOylocWiH3nRABp63v7PLG2tv7u4+LjFYYYc7eRyLI64u9IJ4z3dcuNIvl0S0b/xvCuoxWdfZG5Yuvt1Cu6EVYpwoJBZ5po5pcl3V5HFM3hP2HIyo+tHSpWAP0GDEkx8l3omWdv6g2cUNo86QXpv4gbLRBKJ8hEd98pyLhYw6dN5Qxw2EPHui7cg9zO3XxbOuABmwH8bB0v/nTk3r9/SVjUfVOGN2GJPgk2x3nxFJPCrAYhy/qsh/JxxdbJ1mZytfsEBISYAbEz4y1+pICPurIMRq4lQjNo38bCA46V1m4ih2Sa02CFab91obbJlzHwpa3zicbsXsDWVe4FDIxuqMompIuyqOGLg=
